### ISSUE TITLE
一键部署webase-front 启动不成功

### ISSUE THREAD

**Issue by DevenWW** [WeBankBlockchain/WeBASE#109]
请求帮助，一键部署使用Oraclejdk1.8.0_271和jdk11都报同样的错误。
报错代码：
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'abiController': Unsatisfied dependency expressed through field 'abiService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException

**Comment by CodingCattwo** [comment]
可参考该ISSUE https://github.com/WeBankFinTech/WeBASE-Front/issues/456#issuecomment-729607405
