### ISSUE TITLE
一键部署，webase-sign不存在

### ISSUE THREAD

**Issue by freezehe** [WeBankBlockchain/WeBASE#119]
参考官网手册一键部署，启动所有服务的时候，提示webase-sign不存在。看了一下层级目录，确实没有下载下载webase-sign,截图如下。
![image](https://user-images.githubusercontent.com/11324122/100494285-53b45e00-317b-11eb-8880-e0b259d30409.png)
![image](https://user-images.githubusercontent.com/11324122/100494287-544cf480-317b-11eb-9069-7f71b5dcae8d.png)

**Comment by mingzhenliu** [comment]
执行过程没有报错吗？
