### ISSUE TITLE
webase管理平台，关闭节点管理界面中的前置编号第一个的节点，数据预览模块失常

### ISSUE THREAD

**Issue by chenjinrang** [WeBankBlockchain/WeBASE#132]
![image](https://user-images.githubusercontent.com/72734779/102752448-934e1e80-43a4-11eb-9d38-8c1a9e8102fa.png)
1、关闭如上图中的划线的机构中的节点，会导致整个webase的数据预览模块无法查看

**Comment by CodingCattwo** [comment]
在最新版已修复该问题
