### ISSUE TITLE
合约编译长时间夯死

### ISSUE THREAD

**Issue by crazythinking** [WeBankBlockchain/WeBASE#144]
在合约IDE页面，编译合约时页面长时间夯死，无反应；
F12 发现页面js异常；
![image](https://user-images.githubusercontent.com/5145888/105681812-981a6b00-5f2c-11eb-9ca4-cd7ada8e87f9.png)

**Comment by CodingCattwo** [comment]
错误信息中提示加载solidity的js文件失败。合约较大时编译耗时会较久
