### ISSUE TITLE
WeBASE可视化部署后，进行节点扩容，在“证书管理”中总会多出一份“node”证书

### ISSUE THREAD

**Issue by chuchaochen** [WeBankBlockchain/WeBASE#148]
步骤：
1、可视化部署bcos链。
2、新增节点进行扩容。
3、扩容后，在WeBASE的“证书管理”中可以看到多出一行名称为“node”的证书。例如：我扩容一个节点，证书管理中会新增两个“node”证书；我扩容两个节点，证书管理中会新增三个“node”证书。每一次扩容，都会多出一个多余的“node”。

**Comment by CodingCattwo** [comment]
可视化部署里的扩容节点会在生成节点证书的时候，生成一份属于该节点的新的SDK证书，SDK证书的类型也是“节点”证书。

**Comment by CodingCattwo** [comment]
> 可视化部署里的扩容节点会在生成节点证书的时候，生成一份属于该节点的新的SDK证书，SDK证书的类型也是“节点”证书。

可以通过节点的nodeid进行区分，节点列表中没有的nodeid则是sdk证书
