### ISSUE TITLE
WeBASE可视化部署时，节点所属机构无法维护

### ISSUE THREAD

**Issue by highwindsky** [WeBankBlockchain/WeBASE#149]
通过WeBASE可视化部署链后， 节点所属机构均为“agency1”, 且不可维护。建议完善下，像手动部署一样可维护节点所属的机构。

**Comment by CodingCattwo** [comment]
一个WeBASE默认管理一个机构，如果需要按机构部署，建议通过手动部署链，自定义生成多个机构证书与多个机构下的节点证书，再添加到WeBASE中进行管理

**Comment by CodingCattwo** [comment]
一个WeBASE默认管理一个机构，如果需要按机构部署，建议通过手动部署链，自定义生成多个机构证书与多个机构下的节点证书，再添加到WeBASE中进行管理
