### ISSUE TITLE
关于WeBASE链上角色治理的问题

### ISSUE THREAD

**Issue by highwindsky** [WeBankBlockchain/WeBASE#150]
现在的WeBASE管理平台并不适合“链治理角色”、“运维角色”、“业务角色”和“监管角色”使用，能否提供一套适合这些链上角色使用的管理平台，登录后只能执行权限范围内的操作。

**Comment by CodingCattwo** [comment]
在WeBASE1.5.1后对WeBASE管理台的账号体系（不同于链上的私钥账号）的开发者角色进行了优化，在webase-node-manager的conf/application.yml中修改`developerModeEnable`为true开启开发者模式，登陆后开发者模式仅能查看自己创建的私钥。

**Comment by CodingCattwo** [comment]
基于上述的开发者私钥，可以进行链上私钥和开发者账号进行关联，比如链上运维管理员的私钥通过开发者1账号创建，链上的业务角色通过开发者2账号创建，即可达到角色隔离的效果。
