### ISSUE TITLE
webase.front.Application Port 5002无法启动

### ISSUE THREAD

**Issue by yml666666** [WeBankBlockchain/WeBASE#164]
Server com.webank.webase.front.Application Port 5002 ................................[Failed]. 
端口没有办法启动

**Comment by sunmmerfun** [comment]
我也碰到了这个问题，部署webase之后检查进程端口，发现5002未监听,产看front-error.log有如下异常：
[WeBASE-Front-error.log](https://github.com/WeBankFinTech/WeBASE/files/6368892/WeBASE-Front-error.log)

**Comment by CodingCattwo** [comment]
可以查看webase-front/log中的日志文件排查一下启动失败原因

**Comment by tannnn2022** [comment]
> 
请问，问题解决了吗？我也遇到了一样的问题，不知道应该怎样解决
