### ISSUE TITLE
postman测试WEBASE-Front交易接口，返回"errorMessage": "user's privateKey is null"怎么解决呢？

### ISSUE THREAD

**Issue by 256yangwei** [WeBankBlockchain/WeBASE#175]
我在用WEBASE-Front交易测试交易，合约就是官网的helloworld，我想调用set接口更改字符串，我的请求接口和数据如下：
![image](https://user-images.githubusercontent.com/33602361/124241047-fa1b7400-db4d-11eb-8d47-b3109cd7bb28.png)
返回信息如下，提示"errorMessage": "user's privateKey is null"。
![image](https://user-images.githubusercontent.com/33602361/124241121-0dc6da80-db4e-11eb-8acd-aa83663bf695.png)
请问是如何才能测试成功呢。

PS：我自己现在的理解是交易的过程中可能需要一个用户的签名信息，附加到头信息或者啥地方。提示用户私钥为空，也不应该直接附加私钥信息在发送头或者request请求消息里吧？

**Comment by 256yangwei** [comment]
由于图片不清晰，补充如下

请求方法post, http://ip:5002/WeBASE-Front/trans/handle
请求数据:
{
    "user":"0x810158ce70541180cfe69b211d791b0a7c89fa0e",
    "contractName":"HelloWorld",
    "contractAddress":"0x35bcc6112699e60bcbe6af3c36cb67a4700009c0",
    "funcName":"set",
    "contractAbi":[{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"n","type":"string"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}],
    "funcParam":["Hi,Welcome!"],
    "groupId" :"1",
    "useCns": false
}

返回信息：
{
    "code": 201015,
    "data": null,
    "errorMessage": "user's privateKey is null"
}

**Comment by CodingCattwo** [comment]
填入的user字段应从WeBASE-Front的web页面的“合约管理-测试用户”中获取，比如创建一个新的测试用户。
