### ISSUE TITLE
5.7以上版本MYSQL的模式sql_mode出错

### ISSUE THREAD

**Issue by youwenbusi** [WeBankBlockchain/WeBASE#185]
打开Transaction Audit的Unusal User和Unusual Contract页面出现WeBASE-Node-Manager system exception错误提示，通过日志看到“...this is incompatible with sql_mode=only_full_group_by”的错误，具体缘由百度很多。
先通过select @@GLOBAL.sql_mode; 查看当前的 sql_mode的值；
修改 sql_mode：SET @@GLOBAL.sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_AUTO_CREATE_USER,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'; 如果提示不能设置NO_AUTO_CREATE_USER，则把这个字段去掉。
重启WeBASE-Node-Manager：bash stop.sh&bash start.sh，注意不能重启mysql，否则sql_mode的值又恢复原样，如果要永久修改，可在mysql的配置文件（/etc下的my.cnf文件）末尾添加sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION，重启mysql即可。

**Comment by CodingCattwo** [comment]
最新版webase已适配该兼容性问题
