### ISSUE TITLE
webase-front 中的一个bug

### ISSUE THREAD

**Issue by minchenzz** [WeBankBlockchain/WeBASE#190]
合约管理-在线工具-event查看

如果没有选event名，直接点击查看，提示请选择事件名错误

此时即使重新选择了事件，也不能查看，需要刷新页面才能恢复

**Comment by CodingCattwo** [comment]
感谢反馈，我们优化该bug

**Comment by CodingCattwo** [comment]
已在1.5.4中修复该问题
