### ISSUE TITLE
webase-node-mgr合约数据无法拉取问题

### ISSUE THREAD

**Issue by xp007123** [WeBankBlockchain/WeBASE#192]
情况1 ：
错误前情：服务器在未停止服务的情况下重启，webase无法正常拉取合约数据
错误现象：现区块链网络有两个群组，群组1无法拉取合约数据，群组2正常。区块数据等其他状态皆正常
![image](https://user-images.githubusercontent.com/57866608/134271365-88de6af7-9111-4771-844b-7f7ae3af4935.png)

![image](https://user-images.githubusercontent.com/57866608/134271391-a1cef5da-2780-428e-af34-9733295ccbb9.png)

错误日志：
[WeBASE-Node-Manager-error.log](https://github.com/WeBankFinTech/WeBASE/files/7207245/WeBASE-Node-Manager-error.log)

全量日志：
[WeBASE-Node-Manager.log](https://github.com/WeBankFinTech/WeBASE/files/7207250/WeBASE-Node-Manager.log)

情况2：
错误前情：“群组管理” --> "删除群组数据" 刷新重新加载后，合约数据就无法拉取了
错误现象：现区块链网络有两个群组(与情况1的区块链环境不一样，情况1为单机部署，情况2为多级部署)，群组2在执行刷新群组数据后，合约数据丢失。区块数据等其他状态皆正常。
错误现象：
![image](https://user-images.githubusercontent.com/57866608/134272273-2a105408-1830-459f-890d-3b0238cfb453.png)

错误日志：
[WeBASE-Node-Manager-error.log](https://github.com/WeBankFinTech/WeBASE/files/7207269/WeBASE-Node-Manager-error.log)

全量日志：
[WeBASE-Node-Manager.log](https://github.com/WeBankFinTech/WeBASE/files/7207270/WeBASE-Node-Manager.log)

**Comment by xp007123** [comment]
合约皆是通过webase部署

**Comment by CodingCattwo** [comment]
1. 在console部署的合约可以在最新版webase的“合约管理-全量合约”中找到并导入
2. 如果删除对应群组的合约数据后，将无法恢复合约数据

**Comment by CodingCattwo** [comment]
在WeBASE-Node-Manager 的全量日志中未找到部署合约的相关日志，如果需要在webase管理console部署的合约，可以在最新版webase的“合约管理-全量合约”中找到并导入
