### ISSUE TITLE
webase节点无法初始化

### ISSUE THREAD

**Issue by jrzhu09** [WeBankBlockchain/WeBASE#194]
![image](https://user-images.githubusercontent.com/82650994/134352684-db22d76e-4e95-4c00-bd90-864c57262240.png)

**Comment by jrzhu09** [comment]
webase可视化部署

**Comment by CodingCattwo** [comment]
可视化部署需要结合WeBASE-Node-Manager日志排查部署的具体错误情况，也可根据可视化部署文档检查各项依赖是否已安装
