### ISSUE TITLE
webase-node-mgr异常，加载不出验证码

### ISSUE THREAD

**Issue by lizhijun97** [WeBankBlockchain/WeBASE#197]
[ERROR][2021-10-11 10:10:30.047][node-mgr-async-9][wsweb][2224][2224][LOG_POINT]Unexpected exception occurred invoking async method: public void com.webank.webase.node.mgr.appintegration.AppIntegrationService.appStatusCheck()
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

**Comment by xp007123** [comment]
我也出现了相同的问题，无法解决

**Comment by lizhijun97** [comment]
我后续将jdk11更换8之后，规避了验证码问题。但出现了另一个问题，就是前置节点服务启动就崩溃。你可以试试我的办法，每个人具体环境不同说不定就可以了！

**Comment by mingzhenliu** [comment]
看看内存是不是够？

**Comment by mingzhenliu** [comment]
> 我后续将jdk11更换8之后，规避了验证码问题。但出现了另一个问题，就是前置节点服务启动就崩溃。你可以试试我的办法，每个人具体环境不同说不定就可以了！

看看内存是不是够？最好能贴出环境相关日志
