### ISSUE TITLE
all front of group 1 is stopped

### ISSUE THREAD

**Issue by redDevis** [WeBankBlockchain/WeBASE#198]
返回码202002，用程序掉接口插入数据的时候过一会就这样了，stopAll然后再startAll也不行，求教

**Comment by redDevis** [comment]
**有人么**

**Comment by CodingCattwo** [comment]
需要检查节点的共识状态，可以参考fisco bcos文档查看节点的日志检测节点是否正常共识

**Comment by redDevis** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
