### ISSUE TITLE
webase上数据预览页面显示的节点id列表里的块高和区块列表里的最高块高不一致

### ISSUE THREAD

**Issue by fmlwlher** [WeBankBlockchain/WeBASE#199]
部署完fisco，进行一些交易，然后部署webase，部署完成时块高显示一致，之后进行的所有交易，区块列表里的块高会更新，但是节点id列表里的块高不再更新

**Comment by CodingCattwo** [comment]
节点列表中块高不再更新的话，需要检查该节点的状态是否正常。
