### ISSUE TITLE
Webase界面的数据大屏显示的账户数的含义，具体指的啥账户，或者用啥方式可以修改这个值

### ISSUE THREAD

**Issue by flowerrun** [WeBankBlockchain/WeBASE#219]
Webase界面的数据大屏，上面的账户数在官方文档没有详解，而且用添加webase的用户或者加载区块链生成的新账户都不能改变这个账户数。
看源码，这个字段没有明确的定义，找不到。希望官方可以整理下资料，给我们这些开发者一些启示。

**Comment by flowerrun** [comment]
![84abd38705a1e2e4c7dbbcee73155f3](https://user-images.githubusercontent.com/93572056/160775642-64a97dea-3a68-4ac7-addb-adda458eaedc.png)

**Comment by CodingCattwo** [comment]
当前关联数一直为1，经排查是bug，此处应该与链上发起交易的私钥账户数关联
