### ISSUE TITLE
疑似bug，合约调用int类型参数进行修改，无法输入负数

### ISSUE THREAD

**Issue by dyy8888** [WeBankBlockchain/WeBASE#227]
在进行合约部署后，调用时setvalue int类型的变量，输入负数报错不支持合约参数类型编码

**Comment by CodingCattwo** [comment]
经复现后确认是由于fisco-bcos-java-sdk 2.9.0中的bug，后续修复完成将在此issue跟进。感谢反馈！

**Comment by CodingCattwo** [comment]
fisco-bcos-java-sdk 2.9.1及以后版本已修复
