### ISSUE TITLE
节点监控图显示问题

### ISSUE THREAD

**Issue by printfwtnl** [WeBankBlockchain/WeBASE#231]
![image](https://user-images.githubusercontent.com/58335676/183403602-a539c9b2-2fe3-491a-80ef-7a8f879b4a0c.png)
我一直有个疑问，关于第一个图，区块高度，按理来说高度不应该是一直增加的吗？但这里显示的中间有一部分区块高度是为0了，其他的图也类似，这是因为在这些时刻采集到的数据为0吗？但这些数据不应该是以群组节点里的区块高度为基准吗？我最近写论文会用到这些图表，希望相关开发人员能解答一下我的疑惑。

**Comment by CodingCattwo** [comment]
由于FISCO BCOS不出空块的原因，无交易时块高不变，未出块，WeBASE也就不会保存当时的监控数据。有数据的地方是递增的，未出块的地方块高为null，而在图标中null的默认值为0

**Comment by CodingCattwo** [comment]
由于FISCO BCOS不出空块的原因，无交易时块高不变，未出块，WeBASE也就不会保存当时的监控数据。有数据的地方是递增的，未出块的地方块高为null，而在图标中null的默认值为0
