### ISSUE TITLE
solidity v5.2 编译错误但未抛出问题

### ISSUE THREAD

**Issue by mskzj** [WeBankBlockchain/WeBASE#246]
### 贡献者
陈曦、胡腾、牛伟纳、孟凡治、桂勋、杨文武、孙裕俨、黄世平

### 贡献单位
成都网域复兴科技有限公司

电子科技大学

中国工程物理研究院计算机应用研究所（CAEP, Institute of Computer Application, China Academy of Engineering Physics）

###  环境
Ubuntu20.04

### 问题描述

编译错误：合约function临时变量超过16个后 点击编译显示成功但并未生成bin

![未产生bin](https://user-images.githubusercontent.com/37142215/191932981-854a782e-dfd1-4878-81b1-ebd21cad4920.jpg)

合约出错但并没有抛出错误
![问题未抛出到前端](https://user-images.githubusercontent.com/37142215/191933342-56ba4978-bbbd-4c8d-b7cc-3408c51b6db4.jpg)

**Comment by CodingCattwo** [comment]
该问题已在最新版WeBASE中修复，感谢反馈！
