### ISSUE TITLE
调用前置节点服务交易http接口异常返回201015，是否在webase 管理系统创建的用户无法被前置节点服务识别？

### ISSUE THREAD

**Issue by AdonLuo** [WeBankBlockchain/WeBASE#250]
环境：WeBSAE3.0.0 版本一键部署
1. 在webase 管理系统完成合约创建部署，私钥用户创建，用户A是合约部署者，想通过前置节点的http 接口完成交易调用（http://localhost:5002/WeBASE-Front/trans/handle）
调用情况：如果是查询方法调用成功,如果是需要上链的方法调用失败，提示：A的 user's privateKey is null，接口调用body 中无相关说明
![1668078441484](https://user-images.githubusercontent.com/19642911/201075558-634003de-c2bb-4f5b-a129-bfff49098307.jpg)

2. 在前置节点服务子系统中，单独部署和之前一样的合约、创建用户，用户A1是合约部署者，也是调用（http://localhost:5002/WeBASE-Front/trans/handle）接口，合约中所有方法都成功调用。

上述测试调用的接口都是同一个（http://localhost:5002/WeBASE-Front/trans/handle），参数中user、合约地址是各自创建的，如果user 是由Webase 管理页面创建的提示：
![image](https://user-images.githubusercontent.com/19642911/201075710-5414eb21-df93-41e9-ab9c-cce257576930.png)

请教下：是否在webase 管理系统创建的用户无法被前置节点识别？
![image](https://user-images.githubusercontent.com/19642911/201076321-ddc5e1b7-6645-4d2e-9ff4-b7cf9b1af670.png)

**Comment by zp-1999** [comment]
我也是这个问题，有大神解答下吗？

**Comment by zp-1999** [comment]
> 已确认在WeBase里增加的私钥用户无法被前置节点服务识别，而是由节点管理服务WeBase-Node-Mgr识别，接着要模拟账号登录服务，必须登录后才可使用节点管理服务里定义的接口，可以参考这篇文章：https://www.learnblockchain.cn/article/2821

**Comment by CodingCattwo** [comment]
在WeBASE管理台创建的私钥，需要调用`trans/handleWithSign`接口，传入的是sign服务托管的私钥进行签名，对应传入的字段是`signUserId`
