### ISSUE TITLE
docker一键部署时出错

### ISSUE THREAD

**Issue by ZnCuHHH** [WeBankBlockchain/WeBASE#255]
在使用docker一键部署时，提示ValueError: invalid literal for int() with base 10: 'permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock

**Comment by CodingCattwo** [comment]
检查一下docker服务是否已启动，当前运行的系统用户是否可以免sudo直接使用docker命令。如直接运行`docker ps`
