### ISSUE TITLE
webase-node-mgr运行出错

### ISSUE THREAD

**Issue by krfrr** [WeBankBlockchain/WeBASE#277]
一键部署正常
![image](https://user-images.githubusercontent.com/110095357/236628190-daa2cbc9-ca7a-4ba2-aa8d-c3ace1e5b65e.png)
检查端口时，node-mgr默认端口5001没反应，查看运行状态就是5001 is not running ，启动的话显示也如下
![image](https://user-images.githubusercontent.com/110095357/236628483-fd3ca8d3-115c-49aa-9699-c5c2e4c88c7e.png)
日志信息如下
![image](https://user-images.githubusercontent.com/110095357/236628553-1605e93e-dc57-48f5-8eed-45aaf35d5e8a.png)

**Comment by krfrr** [comment]
解决了，重装了完整的数据库

**Comment by splendidlove** [comment]
你好打扰了，想请问下完整的数据库在哪能找到
