### ISSUE TITLE
h2升级问题求助

### ISSUE THREAD

**Issue by yuhwb** [WeBankBlockchain/WeBASE#282]
webase-front 使用版本1.5.3 数据库h2版本:1.4.200
由于H2有重大漏洞问题，现在需要升级至2.1.214。
在升级过程中 发现数据库不向下兼容，无法读取1.4.x版本数据库持久化的文件，那么是否可以删除原来的数据库持久化文件，重新生成新的数据库文件呢？

**Comment by CodingCattwo** [comment]
h2升级后兼容问题，可以参考webase-front中这个issue，https://github.com/WeBankBlockchain/WeBASE-Front/issues/855
