### ISSUE TITLE
WeBase合约导出Java项目部署问题

### ISSUE THREAD

**Issue by gopherxin** [WeBankBlockchain/WeBASE#283]
通过WeBase合约导出的Java项目是可以集成到本地系统还是必须要独立为一个项目部署呢？我这边集成到项目中后，报出这个异常，
![image](https://github.com/WeBankBlockchain/WeBASE/assets/129851705/2f97f71c-3869-46cf-b4e9-e348d4b57132)

**Comment by CodingCattwo** [comment]
需要作为一个独立项目，因为里面会启动一个单独的java进程。
也可以参考里面的代码，把里面的代码复制到已有的项目里
