### ISSUE TITLE
WeBase一键部署MySQL安装错误

### ISSUE THREAD

**Issue by ZnCuHHH** [WeBankBlockchain/WeBASE#285]

**Comment by ZnCuHHH** [comment]
Ubuntu版本22.04.1，按照教程在root用户下执行命令 sudo apt install mysql-server-5.6 时出错，报错mysql-server-5.6无法获取，具体如图所示
![image](https://github.com/WeBankBlockchain/WeBASE/assets/65380493/1919cf35-0e53-442a-bf1a-a30e8732e116)

**Comment by CodingCattwo** [comment]
可以在webase的部署文档里查看mysql部署章节。如果使用mysql 5.6，对应的应该是mariadb的10.2版本，文档 https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/WeBASE/doc/docs/WeBASE/install.html#id19
